### ISSUE TITLE
Plugin: Gopher

### ISSUE THREAD

**Issue by alehandrof** [statamicthemes/statamicthemes.github.io#5]
http://apocketproduction.com/

(Haven't tried it -- and I'm too lazy to do a PR :)

P.S. Have you tried setting all the filenames of the plugins to the same date? I think that would allow them to alphabetize correctly on the site.

**Comment by garethredfern** [comment]
Thanks Alex added the plugin, looks good. I have also added a sort to almost get things in alphabetical order. It doesn't adhere to case sensitivity, but hey.

**Comment by alehandrof** [comment]
Great! :)
